### ISSUE TITLE
Highlight of sample points is not always working correctly

### ISSUE THREAD

**Issue by jgeudens** [jgeudens/GraphViewer#29]
The highlight of sample points is disabled when there are not enough pixels per sample point. The current implementation fails when the user zooms out too much.

It occurs when the lower bound of the x axis range is smaller than the lower bound of the graph or when the upper bound of the x-axis is greater than the upper bound of the graph.

**Comment by pluyckx** [comment]
I have made a patch for the testing branch. It contains a possible bug, see the patch comment for more information. Beside this scenario, maybe the bug can cause a crash in future releases. So it is better to fix it now, and you can then port this to ModbusScope, where the bug causes a crash.

You can find the patch here: https://gist.github.com/pluyckx/a9e0113821a27db525fe

This patch is made for the testing branch!
