### ISSUE TITLE
Load file with absolute timestamps

### ISSUE THREAD

**Issue by lsteynen** [jgeudens/GraphViewer#39]
Hi,
I want to load a file with absolute date/time column. This seems not to be possible?
For example:
_DateTime;Supply;Exhaust;T1;T2;T3
7/07/2017 16:00:01;3500;3501;28,2;-3,9;24,4
7/07/2017 16:10:01;3499;3500;28,3;-3,8;24,5
7/07/2017 16:20:01;3500;3500;28,4;-3,7;24,6_

**Comment by jgeudens** [comment]
I will support date and times in following formats:

- "17-07-2017 23:45:01.300"
- "17/07/2017 23:45:01.300"
- "17 07 2017 23:45:01.300"
- "7 7 2017 23:45:01,300"
- "7/7/2017 23:45:01,300"
- "7 7 2017 23:45:01"
- "7/7/2017 23:45:01"
